repos:
  - repo: local
    hooks:
      - id: php-cs-fixer
        name: php-cs-fixer
        entry: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --ansi --verbose --diff --dry-run
        language: script
        exclude: '^\.php-cs-fixer\.cache$'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: ^frontend/.*\.(ts|tsx|js|css|html|json)$
        args:
          [
            "--config=./frontend/.prettierrc",
            "--ignore-path=./frontend/.prettierignore",
          ]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.33.0"
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint
          - eslint-config-react-app
          - typescript
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"
          - eslint-config-prettier
          - eslint-plugin-jsx-a11y
          - eslint-plugin-prettier
          - eslint-plugin-react
          - eslint-plugin-react-hooks
        files: ^frontend/.*\.[jt]sx?$
        types: [file]
        args:
          [
            "--config=./frontend/.eslintrc.js",
            "--ignore-path=./frontend/.eslintignore",
          ]
