name: Next

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  next-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Use Node.js 19.5.0'
        uses: actions/setup-node@v3
        with:
          node-version: 19.5.0

      - name: Install Dependencies
        run: cd frontend && npm ci

      - name: Run ESLint and Prettier
        run: cd frontend && npm run style:all

      - name: Build
        run: cd frontend && npm run build
